language: node_js
node_js:
  - "18"
  - "16"
sudo: false
before_install:
  - npm install -g grunt-cli
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
